{% set name = "pyrogram" %}
{% set version = "2.0.59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pyrogram-{{ version }}.tar.gz
  sha256: 57cddc62c0f6c9f23b8d8c3c496d2fe0c83d5b4e26ae4f3e8615374d292796ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyaes
    - pysocks

test:
  source_files:
    - tests
  imports:
    - pyrogram
  commands:
    - pytest -vv tests
    - pip check
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://github.com/pyrogram
  summary: Elegant, modern and asynchronous Telegram MTProto API framework in Python for users and bots
  dev_url: https://github.com/pyrogram/pyrogram
  license: LGPL-3.0-or-later
  license_file:
    - COPYING.lesser
    - NOTICE
    - COPYING

extra:
  recipe-maintainers:
    - nehaljwani
